// Generated by gencpp from file roboy_communication_middleware/DarkRoom.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_DARKROOM_H
#define ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_DARKROOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboy_communication_middleware
{
template <class ContainerAllocator>
struct DarkRoom_
{
  typedef DarkRoom_<ContainerAllocator> Type;

  DarkRoom_()
    : sensor_value()  {
    }
  DarkRoom_(const ContainerAllocator& _alloc)
    : sensor_value(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _sensor_value_type;
  _sensor_value_type sensor_value;




  typedef boost::shared_ptr< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> const> ConstPtr;

}; // struct DarkRoom_

typedef ::roboy_communication_middleware::DarkRoom_<std::allocator<void> > DarkRoom;

typedef boost::shared_ptr< ::roboy_communication_middleware::DarkRoom > DarkRoomPtr;
typedef boost::shared_ptr< ::roboy_communication_middleware::DarkRoom const> DarkRoomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboy_communication_middleware

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roboy_communication_middleware': ['/home/roboy/workspace/myoarm_small_FPGA/src/roboy_communication/middleware/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe9f107384ef1fa35761a92979cb2251";
  }

  static const char* value(const ::roboy_communication_middleware::DarkRoom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe9f107384ef1fa3ULL;
  static const uint64_t static_value2 = 0x5761a92979cb2251ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboy_communication_middleware/DarkRoom";
  }

  static const char* value(const ::roboy_communication_middleware::DarkRoom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32[] sensor_value\n\
";
  }

  static const char* value(const ::roboy_communication_middleware::DarkRoom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensor_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DarkRoom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboy_communication_middleware::DarkRoom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboy_communication_middleware::DarkRoom_<ContainerAllocator>& v)
  {
    s << indent << "sensor_value[]" << std::endl;
    for (size_t i = 0; i < v.sensor_value.size(); ++i)
    {
      s << indent << "  sensor_value[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.sensor_value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOY_COMMUNICATION_MIDDLEWARE_MESSAGE_DARKROOM_H
