// Generated by gencpp from file roboy_communication_control/PerformMovement.msg
// DO NOT EDIT!


#ifndef ROBOY_COMMUNICATION_CONTROL_MESSAGE_PERFORMMOVEMENT_H
#define ROBOY_COMMUNICATION_CONTROL_MESSAGE_PERFORMMOVEMENT_H

#include <ros/service_traits.h>


#include <roboy_communication_control/PerformMovementRequest.h>
#include <roboy_communication_control/PerformMovementResponse.h>


namespace roboy_communication_control
{

struct PerformMovement
{

typedef PerformMovementRequest Request;
typedef PerformMovementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PerformMovement
} // namespace roboy_communication_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboy_communication_control::PerformMovement > {
  static const char* value()
  {
    return "0462bc0e878964615c49ad8ef45df667";
  }

  static const char* value(const ::roboy_communication_control::PerformMovement&) { return value(); }
};

template<>
struct DataType< ::roboy_communication_control::PerformMovement > {
  static const char* value()
  {
    return "roboy_communication_control/PerformMovement";
  }

  static const char* value(const ::roboy_communication_control::PerformMovement&) { return value(); }
};


// service_traits::MD5Sum< ::roboy_communication_control::PerformMovementRequest> should match 
// service_traits::MD5Sum< ::roboy_communication_control::PerformMovement > 
template<>
struct MD5Sum< ::roboy_communication_control::PerformMovementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_control::PerformMovement >::value();
  }
  static const char* value(const ::roboy_communication_control::PerformMovementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_control::PerformMovementRequest> should match 
// service_traits::DataType< ::roboy_communication_control::PerformMovement > 
template<>
struct DataType< ::roboy_communication_control::PerformMovementRequest>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_control::PerformMovement >::value();
  }
  static const char* value(const ::roboy_communication_control::PerformMovementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboy_communication_control::PerformMovementResponse> should match 
// service_traits::MD5Sum< ::roboy_communication_control::PerformMovement > 
template<>
struct MD5Sum< ::roboy_communication_control::PerformMovementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboy_communication_control::PerformMovement >::value();
  }
  static const char* value(const ::roboy_communication_control::PerformMovementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboy_communication_control::PerformMovementResponse> should match 
// service_traits::DataType< ::roboy_communication_control::PerformMovement > 
template<>
struct DataType< ::roboy_communication_control::PerformMovementResponse>
{
  static const char* value()
  {
    return DataType< ::roboy_communication_control::PerformMovement >::value();
  }
  static const char* value(const ::roboy_communication_control::PerformMovementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOY_COMMUNICATION_CONTROL_MESSAGE_PERFORMMOVEMENT_H
