(cl:defpackage roboy_communication_control-msg
  (:use )
  (:export
   "<DANGERNOTIFICATION>"
   "DANGERNOTIFICATION"
   "<DEBUGNOTIFICATION>"
   "DEBUGNOTIFICATION"
   "<EMOTION>"
   "EMOTION"
   "<ERRORNOTIFICATION>"
   "ERRORNOTIFICATION"
   "<INFONOTIFICATION>"
   "INFONOTIFICATION"
   "<WARNINGNOTIFICATION>"
   "WARNINGNOTIFICATION"
  ))

